spring:
security:
urls:
  cognito: https://bambam-client.auth.us-east-1.amazoncognito.com/
endpoints:
  authorize: https://bambam-client.auth.us-east-1.amazoncognito.com/oauth2/authorize?response_type=code&client_id=n5l1l6id094g0lk2f3vc1h6h7&redirect_uri=http://d2iny48xdni2vj.cloudfront.net/dashboard
  token: https://bambam-client.auth.us-east-1.amazoncognito.com/oauth2/token
cognito:
  client: 
  secret: 
  callback: http://d2iny48xdni2vj.cloudfront.net/dashboard
  keys: https://cognito-idp.auth.us-east-1.amazonaws.com/_7bWZrc3vS/.well-known/jwks.json
  scope: aws.cognito.signin.user.admin